export const DEFAULT_VALUES = {
    constructionDate: new Date(),
    reference: "",
    camera: false,
    security: false,
    elevator: false,
    parking: false,
    pool: false,
    generator: false,
    waterBorehole: false,
    gym: false,
    garden: false,
    name: "",
    location: "",
    lotType: [],
    status: [],
    map: "30.000000000, 21.000000000",
    photos: undefined,
    deeds: undefined,
    documents: undefined,
};