/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUnitsIndexRouteImport } from './routes/dashboard/units/index'
import { Route as DashboardTenantsIndexRouteImport } from './routes/dashboard/tenants/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardServiceProvidersIndexRouteImport } from './routes/dashboard/service-providers/index'
import { Route as DashboardReservationsIndexRouteImport } from './routes/dashboard/reservations/index'
import { Route as DashboardReportsIndexRouteImport } from './routes/dashboard/reports/index'
import { Route as DashboardRentalsIndexRouteImport } from './routes/dashboard/rentals/index'
import { Route as DashboardPropertyManagementIndexRouteImport } from './routes/dashboard/property-management/index'
import { Route as DashboardOwnersIndexRouteImport } from './routes/dashboard/owners/index'
import { Route as DashboardInvoicesIndexRouteImport } from './routes/dashboard/invoices/index'
import { Route as DashboardContractsIndexRouteImport } from './routes/dashboard/contracts/index'
import { Route as DashboardCommunicationsIndexRouteImport } from './routes/dashboard/communications/index'
import { Route as DashboardBuildingsIndexRouteImport } from './routes/dashboard/buildings/index'
import { Route as DashboardAppointmentsIndexRouteImport } from './routes/dashboard/appointments/index'
import { Route as DashboardAccountingIndexRouteImport } from './routes/dashboard/accounting/index'
import { Route as DashboardUnitsNewUnitRouteImport } from './routes/dashboard/units/new-unit'
import { Route as DashboardUnitsIdRouteImport } from './routes/dashboard/units/$id'
import { Route as DashboardTenantsNewTenantRouteImport } from './routes/dashboard/tenants/new-tenant'
import { Route as DashboardTenantsIdRouteImport } from './routes/dashboard/tenants/$id'
import { Route as DashboardServiceProvidersNewServiceRouteImport } from './routes/dashboard/service-providers/new-service'
import { Route as DashboardServiceProvidersIdRouteImport } from './routes/dashboard/service-providers/$id'
import { Route as DashboardReservationsNewReservationRouteImport } from './routes/dashboard/reservations/new-reservation'
import { Route as DashboardReservationsIdRouteImport } from './routes/dashboard/reservations/$id'
import { Route as DashboardReportsNewReportRouteImport } from './routes/dashboard/reports/new-report'
import { Route as DashboardReportsIdRouteImport } from './routes/dashboard/reports/$id'
import { Route as DashboardRentalsNewRentalRouteImport } from './routes/dashboard/rentals/new-rental'
import { Route as DashboardRentalsIdRouteImport } from './routes/dashboard/rentals/$id'
import { Route as DashboardPropertyManagementNewPropertyRouteImport } from './routes/dashboard/property-management/new-property'
import { Route as DashboardPropertyManagementIdRouteImport } from './routes/dashboard/property-management/$id'
import { Route as DashboardOwnersNewOwnerRouteImport } from './routes/dashboard/owners/new-owner'
import { Route as DashboardOwnersIdRouteImport } from './routes/dashboard/owners/$id'
import { Route as DashboardInvoicesNewInvoiceRouteImport } from './routes/dashboard/invoices/new-invoice'
import { Route as DashboardInvoicesIdRouteImport } from './routes/dashboard/invoices/$id'
import { Route as DashboardContractsNewContractRouteImport } from './routes/dashboard/contracts/new-contract'
import { Route as DashboardContractsIdRouteImport } from './routes/dashboard/contracts/$id'
import { Route as DashboardCommunicationsNewCommunicationRouteImport } from './routes/dashboard/communications/new-communication'
import { Route as DashboardCommunicationsIdRouteImport } from './routes/dashboard/communications/$id'
import { Route as DashboardBuildingsNewBuildingRouteImport } from './routes/dashboard/buildings/new-building'
import { Route as DashboardBuildingsIdRouteImport } from './routes/dashboard/buildings/$id'
import { Route as DashboardAppointmentsNewAppointmentRouteImport } from './routes/dashboard/appointments/new-appointment'
import { Route as DashboardAppointmentsIdRouteImport } from './routes/dashboard/appointments/$id'
import { Route as DashboardAccountingNewAccountingRouteImport } from './routes/dashboard/accounting/new-accounting'
import { Route as DashboardAccountingIdRouteImport } from './routes/dashboard/accounting/$id'
import { Route as DashboardUnitsEditUnitIdRouteImport } from './routes/dashboard/units/edit-unit.$id'
import { Route as DashboardTenantsEditTenantIdRouteImport } from './routes/dashboard/tenants/edit-tenant.$id'
import { Route as DashboardServiceProvidersEditServiceIdRouteImport } from './routes/dashboard/service-providers/edit-service.$id'
import { Route as DashboardReservationsEditReservationIdRouteImport } from './routes/dashboard/reservations/edit-reservation.$id'
import { Route as DashboardReportsEditReportIdRouteImport } from './routes/dashboard/reports/edit-report.$id'
import { Route as DashboardRentalsEditRentalIdRouteImport } from './routes/dashboard/rentals/edit-rental.$id'
import { Route as DashboardPropertyManagementEditPropertyIdRouteImport } from './routes/dashboard/property-management/edit-property.$id'
import { Route as DashboardOwnersEditOwnerIdRouteImport } from './routes/dashboard/owners/edit-owner.$id'
import { Route as DashboardInvoicesEditInvoiceIdRouteImport } from './routes/dashboard/invoices/edit-invoice.$id'
import { Route as DashboardContractsEditContractIdRouteImport } from './routes/dashboard/contracts/edit-contract.$id'
import { Route as DashboardCommunicationsEditCommunicationIdRouteImport } from './routes/dashboard/communications/edit-communication.$id'
import { Route as DashboardBuildingsEditBuildingIdRouteImport } from './routes/dashboard/buildings/edit-building.$id'
import { Route as DashboardAppointmentsEditAppointmentIdRouteImport } from './routes/dashboard/appointments/edit-appointment.$id'
import { Route as DashboardAccountingEditAccountingIdRouteImport } from './routes/dashboard/accounting/edit-accounting.$id'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUnitsIndexRoute = DashboardUnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTenantsIndexRoute = DashboardTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardServiceProvidersIndexRoute =
  DashboardServiceProvidersIndexRouteImport.update({
    id: '/service-providers/',
    path: '/service-providers/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardReservationsIndexRoute =
  DashboardReservationsIndexRouteImport.update({
    id: '/reservations/',
    path: '/reservations/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardReportsIndexRoute = DashboardReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRentalsIndexRoute = DashboardRentalsIndexRouteImport.update({
  id: '/rentals/',
  path: '/rentals/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPropertyManagementIndexRoute =
  DashboardPropertyManagementIndexRouteImport.update({
    id: '/property-management/',
    path: '/property-management/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOwnersIndexRoute = DashboardOwnersIndexRouteImport.update({
  id: '/owners/',
  path: '/owners/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInvoicesIndexRoute = DashboardInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContractsIndexRoute = DashboardContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCommunicationsIndexRoute =
  DashboardCommunicationsIndexRouteImport.update({
    id: '/communications/',
    path: '/communications/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBuildingsIndexRoute = DashboardBuildingsIndexRouteImport.update({
  id: '/buildings/',
  path: '/buildings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAppointmentsIndexRoute =
  DashboardAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountingIndexRoute =
  DashboardAccountingIndexRouteImport.update({
    id: '/accounting/',
    path: '/accounting/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardUnitsNewUnitRoute = DashboardUnitsNewUnitRouteImport.update({
  id: '/units/new-unit',
  path: '/units/new-unit',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUnitsIdRoute = DashboardUnitsIdRouteImport.update({
  id: '/units/$id',
  path: '/units/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTenantsNewTenantRoute =
  DashboardTenantsNewTenantRouteImport.update({
    id: '/tenants/new-tenant',
    path: '/tenants/new-tenant',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTenantsIdRoute = DashboardTenantsIdRouteImport.update({
  id: '/tenants/$id',
  path: '/tenants/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardServiceProvidersNewServiceRoute =
  DashboardServiceProvidersNewServiceRouteImport.update({
    id: '/service-providers/new-service',
    path: '/service-providers/new-service',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardServiceProvidersIdRoute =
  DashboardServiceProvidersIdRouteImport.update({
    id: '/service-providers/$id',
    path: '/service-providers/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardReservationsNewReservationRoute =
  DashboardReservationsNewReservationRouteImport.update({
    id: '/reservations/new-reservation',
    path: '/reservations/new-reservation',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardReservationsIdRoute = DashboardReservationsIdRouteImport.update({
  id: '/reservations/$id',
  path: '/reservations/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReportsNewReportRoute =
  DashboardReportsNewReportRouteImport.update({
    id: '/reports/new-report',
    path: '/reports/new-report',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardReportsIdRoute = DashboardReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRentalsNewRentalRoute =
  DashboardRentalsNewRentalRouteImport.update({
    id: '/rentals/new-rental',
    path: '/rentals/new-rental',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardRentalsIdRoute = DashboardRentalsIdRouteImport.update({
  id: '/rentals/$id',
  path: '/rentals/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPropertyManagementNewPropertyRoute =
  DashboardPropertyManagementNewPropertyRouteImport.update({
    id: '/property-management/new-property',
    path: '/property-management/new-property',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPropertyManagementIdRoute =
  DashboardPropertyManagementIdRouteImport.update({
    id: '/property-management/$id',
    path: '/property-management/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOwnersNewOwnerRoute = DashboardOwnersNewOwnerRouteImport.update({
  id: '/owners/new-owner',
  path: '/owners/new-owner',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOwnersIdRoute = DashboardOwnersIdRouteImport.update({
  id: '/owners/$id',
  path: '/owners/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInvoicesNewInvoiceRoute =
  DashboardInvoicesNewInvoiceRouteImport.update({
    id: '/invoices/new-invoice',
    path: '/invoices/new-invoice',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardInvoicesIdRoute = DashboardInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContractsNewContractRoute =
  DashboardContractsNewContractRouteImport.update({
    id: '/contracts/new-contract',
    path: '/contracts/new-contract',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardContractsIdRoute = DashboardContractsIdRouteImport.update({
  id: '/contracts/$id',
  path: '/contracts/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCommunicationsNewCommunicationRoute =
  DashboardCommunicationsNewCommunicationRouteImport.update({
    id: '/communications/new-communication',
    path: '/communications/new-communication',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCommunicationsIdRoute =
  DashboardCommunicationsIdRouteImport.update({
    id: '/communications/$id',
    path: '/communications/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBuildingsNewBuildingRoute =
  DashboardBuildingsNewBuildingRouteImport.update({
    id: '/buildings/new-building',
    path: '/buildings/new-building',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBuildingsIdRoute = DashboardBuildingsIdRouteImport.update({
  id: '/buildings/$id',
  path: '/buildings/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAppointmentsNewAppointmentRoute =
  DashboardAppointmentsNewAppointmentRouteImport.update({
    id: '/appointments/new-appointment',
    path: '/appointments/new-appointment',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAppointmentsIdRoute = DashboardAppointmentsIdRouteImport.update({
  id: '/appointments/$id',
  path: '/appointments/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountingNewAccountingRoute =
  DashboardAccountingNewAccountingRouteImport.update({
    id: '/accounting/new-accounting',
    path: '/accounting/new-accounting',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountingIdRoute = DashboardAccountingIdRouteImport.update({
  id: '/accounting/$id',
  path: '/accounting/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUnitsEditUnitIdRoute =
  DashboardUnitsEditUnitIdRouteImport.update({
    id: '/units/edit-unit/$id',
    path: '/units/edit-unit/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTenantsEditTenantIdRoute =
  DashboardTenantsEditTenantIdRouteImport.update({
    id: '/tenants/edit-tenant/$id',
    path: '/tenants/edit-tenant/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardServiceProvidersEditServiceIdRoute =
  DashboardServiceProvidersEditServiceIdRouteImport.update({
    id: '/service-providers/edit-service/$id',
    path: '/service-providers/edit-service/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardReservationsEditReservationIdRoute =
  DashboardReservationsEditReservationIdRouteImport.update({
    id: '/reservations/edit-reservation/$id',
    path: '/reservations/edit-reservation/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardReportsEditReportIdRoute =
  DashboardReportsEditReportIdRouteImport.update({
    id: '/reports/edit-report/$id',
    path: '/reports/edit-report/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardRentalsEditRentalIdRoute =
  DashboardRentalsEditRentalIdRouteImport.update({
    id: '/rentals/edit-rental/$id',
    path: '/rentals/edit-rental/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPropertyManagementEditPropertyIdRoute =
  DashboardPropertyManagementEditPropertyIdRouteImport.update({
    id: '/property-management/edit-property/$id',
    path: '/property-management/edit-property/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOwnersEditOwnerIdRoute =
  DashboardOwnersEditOwnerIdRouteImport.update({
    id: '/owners/edit-owner/$id',
    path: '/owners/edit-owner/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardInvoicesEditInvoiceIdRoute =
  DashboardInvoicesEditInvoiceIdRouteImport.update({
    id: '/invoices/edit-invoice/$id',
    path: '/invoices/edit-invoice/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardContractsEditContractIdRoute =
  DashboardContractsEditContractIdRouteImport.update({
    id: '/contracts/edit-contract/$id',
    path: '/contracts/edit-contract/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCommunicationsEditCommunicationIdRoute =
  DashboardCommunicationsEditCommunicationIdRouteImport.update({
    id: '/communications/edit-communication/$id',
    path: '/communications/edit-communication/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBuildingsEditBuildingIdRoute =
  DashboardBuildingsEditBuildingIdRouteImport.update({
    id: '/buildings/edit-building/$id',
    path: '/buildings/edit-building/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAppointmentsEditAppointmentIdRoute =
  DashboardAppointmentsEditAppointmentIdRouteImport.update({
    id: '/appointments/edit-appointment/$id',
    path: '/appointments/edit-appointment/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountingEditAccountingIdRoute =
  DashboardAccountingEditAccountingIdRouteImport.update({
    id: '/accounting/edit-accounting/$id',
    path: '/accounting/edit-accounting/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/accounting/$id': typeof DashboardAccountingIdRoute
  '/dashboard/accounting/new-accounting': typeof DashboardAccountingNewAccountingRoute
  '/dashboard/appointments/$id': typeof DashboardAppointmentsIdRoute
  '/dashboard/appointments/new-appointment': typeof DashboardAppointmentsNewAppointmentRoute
  '/dashboard/buildings/$id': typeof DashboardBuildingsIdRoute
  '/dashboard/buildings/new-building': typeof DashboardBuildingsNewBuildingRoute
  '/dashboard/communications/$id': typeof DashboardCommunicationsIdRoute
  '/dashboard/communications/new-communication': typeof DashboardCommunicationsNewCommunicationRoute
  '/dashboard/contracts/$id': typeof DashboardContractsIdRoute
  '/dashboard/contracts/new-contract': typeof DashboardContractsNewContractRoute
  '/dashboard/invoices/$id': typeof DashboardInvoicesIdRoute
  '/dashboard/invoices/new-invoice': typeof DashboardInvoicesNewInvoiceRoute
  '/dashboard/owners/$id': typeof DashboardOwnersIdRoute
  '/dashboard/owners/new-owner': typeof DashboardOwnersNewOwnerRoute
  '/dashboard/property-management/$id': typeof DashboardPropertyManagementIdRoute
  '/dashboard/property-management/new-property': typeof DashboardPropertyManagementNewPropertyRoute
  '/dashboard/rentals/$id': typeof DashboardRentalsIdRoute
  '/dashboard/rentals/new-rental': typeof DashboardRentalsNewRentalRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/dashboard/reports/new-report': typeof DashboardReportsNewReportRoute
  '/dashboard/reservations/$id': typeof DashboardReservationsIdRoute
  '/dashboard/reservations/new-reservation': typeof DashboardReservationsNewReservationRoute
  '/dashboard/service-providers/$id': typeof DashboardServiceProvidersIdRoute
  '/dashboard/service-providers/new-service': typeof DashboardServiceProvidersNewServiceRoute
  '/dashboard/tenants/$id': typeof DashboardTenantsIdRoute
  '/dashboard/tenants/new-tenant': typeof DashboardTenantsNewTenantRoute
  '/dashboard/units/$id': typeof DashboardUnitsIdRoute
  '/dashboard/units/new-unit': typeof DashboardUnitsNewUnitRoute
  '/dashboard/accounting': typeof DashboardAccountingIndexRoute
  '/dashboard/appointments': typeof DashboardAppointmentsIndexRoute
  '/dashboard/buildings': typeof DashboardBuildingsIndexRoute
  '/dashboard/communications': typeof DashboardCommunicationsIndexRoute
  '/dashboard/contracts': typeof DashboardContractsIndexRoute
  '/dashboard/invoices': typeof DashboardInvoicesIndexRoute
  '/dashboard/owners': typeof DashboardOwnersIndexRoute
  '/dashboard/property-management': typeof DashboardPropertyManagementIndexRoute
  '/dashboard/rentals': typeof DashboardRentalsIndexRoute
  '/dashboard/reports': typeof DashboardReportsIndexRoute
  '/dashboard/reservations': typeof DashboardReservationsIndexRoute
  '/dashboard/service-providers': typeof DashboardServiceProvidersIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/tenants': typeof DashboardTenantsIndexRoute
  '/dashboard/units': typeof DashboardUnitsIndexRoute
  '/dashboard/accounting/edit-accounting/$id': typeof DashboardAccountingEditAccountingIdRoute
  '/dashboard/appointments/edit-appointment/$id': typeof DashboardAppointmentsEditAppointmentIdRoute
  '/dashboard/buildings/edit-building/$id': typeof DashboardBuildingsEditBuildingIdRoute
  '/dashboard/communications/edit-communication/$id': typeof DashboardCommunicationsEditCommunicationIdRoute
  '/dashboard/contracts/edit-contract/$id': typeof DashboardContractsEditContractIdRoute
  '/dashboard/invoices/edit-invoice/$id': typeof DashboardInvoicesEditInvoiceIdRoute
  '/dashboard/owners/edit-owner/$id': typeof DashboardOwnersEditOwnerIdRoute
  '/dashboard/property-management/edit-property/$id': typeof DashboardPropertyManagementEditPropertyIdRoute
  '/dashboard/rentals/edit-rental/$id': typeof DashboardRentalsEditRentalIdRoute
  '/dashboard/reports/edit-report/$id': typeof DashboardReportsEditReportIdRoute
  '/dashboard/reservations/edit-reservation/$id': typeof DashboardReservationsEditReservationIdRoute
  '/dashboard/service-providers/edit-service/$id': typeof DashboardServiceProvidersEditServiceIdRoute
  '/dashboard/tenants/edit-tenant/$id': typeof DashboardTenantsEditTenantIdRoute
  '/dashboard/units/edit-unit/$id': typeof DashboardUnitsEditUnitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/accounting/$id': typeof DashboardAccountingIdRoute
  '/dashboard/accounting/new-accounting': typeof DashboardAccountingNewAccountingRoute
  '/dashboard/appointments/$id': typeof DashboardAppointmentsIdRoute
  '/dashboard/appointments/new-appointment': typeof DashboardAppointmentsNewAppointmentRoute
  '/dashboard/buildings/$id': typeof DashboardBuildingsIdRoute
  '/dashboard/buildings/new-building': typeof DashboardBuildingsNewBuildingRoute
  '/dashboard/communications/$id': typeof DashboardCommunicationsIdRoute
  '/dashboard/communications/new-communication': typeof DashboardCommunicationsNewCommunicationRoute
  '/dashboard/contracts/$id': typeof DashboardContractsIdRoute
  '/dashboard/contracts/new-contract': typeof DashboardContractsNewContractRoute
  '/dashboard/invoices/$id': typeof DashboardInvoicesIdRoute
  '/dashboard/invoices/new-invoice': typeof DashboardInvoicesNewInvoiceRoute
  '/dashboard/owners/$id': typeof DashboardOwnersIdRoute
  '/dashboard/owners/new-owner': typeof DashboardOwnersNewOwnerRoute
  '/dashboard/property-management/$id': typeof DashboardPropertyManagementIdRoute
  '/dashboard/property-management/new-property': typeof DashboardPropertyManagementNewPropertyRoute
  '/dashboard/rentals/$id': typeof DashboardRentalsIdRoute
  '/dashboard/rentals/new-rental': typeof DashboardRentalsNewRentalRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/dashboard/reports/new-report': typeof DashboardReportsNewReportRoute
  '/dashboard/reservations/$id': typeof DashboardReservationsIdRoute
  '/dashboard/reservations/new-reservation': typeof DashboardReservationsNewReservationRoute
  '/dashboard/service-providers/$id': typeof DashboardServiceProvidersIdRoute
  '/dashboard/service-providers/new-service': typeof DashboardServiceProvidersNewServiceRoute
  '/dashboard/tenants/$id': typeof DashboardTenantsIdRoute
  '/dashboard/tenants/new-tenant': typeof DashboardTenantsNewTenantRoute
  '/dashboard/units/$id': typeof DashboardUnitsIdRoute
  '/dashboard/units/new-unit': typeof DashboardUnitsNewUnitRoute
  '/dashboard/accounting': typeof DashboardAccountingIndexRoute
  '/dashboard/appointments': typeof DashboardAppointmentsIndexRoute
  '/dashboard/buildings': typeof DashboardBuildingsIndexRoute
  '/dashboard/communications': typeof DashboardCommunicationsIndexRoute
  '/dashboard/contracts': typeof DashboardContractsIndexRoute
  '/dashboard/invoices': typeof DashboardInvoicesIndexRoute
  '/dashboard/owners': typeof DashboardOwnersIndexRoute
  '/dashboard/property-management': typeof DashboardPropertyManagementIndexRoute
  '/dashboard/rentals': typeof DashboardRentalsIndexRoute
  '/dashboard/reports': typeof DashboardReportsIndexRoute
  '/dashboard/reservations': typeof DashboardReservationsIndexRoute
  '/dashboard/service-providers': typeof DashboardServiceProvidersIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/tenants': typeof DashboardTenantsIndexRoute
  '/dashboard/units': typeof DashboardUnitsIndexRoute
  '/dashboard/accounting/edit-accounting/$id': typeof DashboardAccountingEditAccountingIdRoute
  '/dashboard/appointments/edit-appointment/$id': typeof DashboardAppointmentsEditAppointmentIdRoute
  '/dashboard/buildings/edit-building/$id': typeof DashboardBuildingsEditBuildingIdRoute
  '/dashboard/communications/edit-communication/$id': typeof DashboardCommunicationsEditCommunicationIdRoute
  '/dashboard/contracts/edit-contract/$id': typeof DashboardContractsEditContractIdRoute
  '/dashboard/invoices/edit-invoice/$id': typeof DashboardInvoicesEditInvoiceIdRoute
  '/dashboard/owners/edit-owner/$id': typeof DashboardOwnersEditOwnerIdRoute
  '/dashboard/property-management/edit-property/$id': typeof DashboardPropertyManagementEditPropertyIdRoute
  '/dashboard/rentals/edit-rental/$id': typeof DashboardRentalsEditRentalIdRoute
  '/dashboard/reports/edit-report/$id': typeof DashboardReportsEditReportIdRoute
  '/dashboard/reservations/edit-reservation/$id': typeof DashboardReservationsEditReservationIdRoute
  '/dashboard/service-providers/edit-service/$id': typeof DashboardServiceProvidersEditServiceIdRoute
  '/dashboard/tenants/edit-tenant/$id': typeof DashboardTenantsEditTenantIdRoute
  '/dashboard/units/edit-unit/$id': typeof DashboardUnitsEditUnitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/accounting/$id': typeof DashboardAccountingIdRoute
  '/dashboard/accounting/new-accounting': typeof DashboardAccountingNewAccountingRoute
  '/dashboard/appointments/$id': typeof DashboardAppointmentsIdRoute
  '/dashboard/appointments/new-appointment': typeof DashboardAppointmentsNewAppointmentRoute
  '/dashboard/buildings/$id': typeof DashboardBuildingsIdRoute
  '/dashboard/buildings/new-building': typeof DashboardBuildingsNewBuildingRoute
  '/dashboard/communications/$id': typeof DashboardCommunicationsIdRoute
  '/dashboard/communications/new-communication': typeof DashboardCommunicationsNewCommunicationRoute
  '/dashboard/contracts/$id': typeof DashboardContractsIdRoute
  '/dashboard/contracts/new-contract': typeof DashboardContractsNewContractRoute
  '/dashboard/invoices/$id': typeof DashboardInvoicesIdRoute
  '/dashboard/invoices/new-invoice': typeof DashboardInvoicesNewInvoiceRoute
  '/dashboard/owners/$id': typeof DashboardOwnersIdRoute
  '/dashboard/owners/new-owner': typeof DashboardOwnersNewOwnerRoute
  '/dashboard/property-management/$id': typeof DashboardPropertyManagementIdRoute
  '/dashboard/property-management/new-property': typeof DashboardPropertyManagementNewPropertyRoute
  '/dashboard/rentals/$id': typeof DashboardRentalsIdRoute
  '/dashboard/rentals/new-rental': typeof DashboardRentalsNewRentalRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRoute
  '/dashboard/reports/new-report': typeof DashboardReportsNewReportRoute
  '/dashboard/reservations/$id': typeof DashboardReservationsIdRoute
  '/dashboard/reservations/new-reservation': typeof DashboardReservationsNewReservationRoute
  '/dashboard/service-providers/$id': typeof DashboardServiceProvidersIdRoute
  '/dashboard/service-providers/new-service': typeof DashboardServiceProvidersNewServiceRoute
  '/dashboard/tenants/$id': typeof DashboardTenantsIdRoute
  '/dashboard/tenants/new-tenant': typeof DashboardTenantsNewTenantRoute
  '/dashboard/units/$id': typeof DashboardUnitsIdRoute
  '/dashboard/units/new-unit': typeof DashboardUnitsNewUnitRoute
  '/dashboard/accounting/': typeof DashboardAccountingIndexRoute
  '/dashboard/appointments/': typeof DashboardAppointmentsIndexRoute
  '/dashboard/buildings/': typeof DashboardBuildingsIndexRoute
  '/dashboard/communications/': typeof DashboardCommunicationsIndexRoute
  '/dashboard/contracts/': typeof DashboardContractsIndexRoute
  '/dashboard/invoices/': typeof DashboardInvoicesIndexRoute
  '/dashboard/owners/': typeof DashboardOwnersIndexRoute
  '/dashboard/property-management/': typeof DashboardPropertyManagementIndexRoute
  '/dashboard/rentals/': typeof DashboardRentalsIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/dashboard/reservations/': typeof DashboardReservationsIndexRoute
  '/dashboard/service-providers/': typeof DashboardServiceProvidersIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/tenants/': typeof DashboardTenantsIndexRoute
  '/dashboard/units/': typeof DashboardUnitsIndexRoute
  '/dashboard/accounting/edit-accounting/$id': typeof DashboardAccountingEditAccountingIdRoute
  '/dashboard/appointments/edit-appointment/$id': typeof DashboardAppointmentsEditAppointmentIdRoute
  '/dashboard/buildings/edit-building/$id': typeof DashboardBuildingsEditBuildingIdRoute
  '/dashboard/communications/edit-communication/$id': typeof DashboardCommunicationsEditCommunicationIdRoute
  '/dashboard/contracts/edit-contract/$id': typeof DashboardContractsEditContractIdRoute
  '/dashboard/invoices/edit-invoice/$id': typeof DashboardInvoicesEditInvoiceIdRoute
  '/dashboard/owners/edit-owner/$id': typeof DashboardOwnersEditOwnerIdRoute
  '/dashboard/property-management/edit-property/$id': typeof DashboardPropertyManagementEditPropertyIdRoute
  '/dashboard/rentals/edit-rental/$id': typeof DashboardRentalsEditRentalIdRoute
  '/dashboard/reports/edit-report/$id': typeof DashboardReportsEditReportIdRoute
  '/dashboard/reservations/edit-reservation/$id': typeof DashboardReservationsEditReservationIdRoute
  '/dashboard/service-providers/edit-service/$id': typeof DashboardServiceProvidersEditServiceIdRoute
  '/dashboard/tenants/edit-tenant/$id': typeof DashboardTenantsEditTenantIdRoute
  '/dashboard/units/edit-unit/$id': typeof DashboardUnitsEditUnitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/accounting/$id'
    | '/dashboard/accounting/new-accounting'
    | '/dashboard/appointments/$id'
    | '/dashboard/appointments/new-appointment'
    | '/dashboard/buildings/$id'
    | '/dashboard/buildings/new-building'
    | '/dashboard/communications/$id'
    | '/dashboard/communications/new-communication'
    | '/dashboard/contracts/$id'
    | '/dashboard/contracts/new-contract'
    | '/dashboard/invoices/$id'
    | '/dashboard/invoices/new-invoice'
    | '/dashboard/owners/$id'
    | '/dashboard/owners/new-owner'
    | '/dashboard/property-management/$id'
    | '/dashboard/property-management/new-property'
    | '/dashboard/rentals/$id'
    | '/dashboard/rentals/new-rental'
    | '/dashboard/reports/$id'
    | '/dashboard/reports/new-report'
    | '/dashboard/reservations/$id'
    | '/dashboard/reservations/new-reservation'
    | '/dashboard/service-providers/$id'
    | '/dashboard/service-providers/new-service'
    | '/dashboard/tenants/$id'
    | '/dashboard/tenants/new-tenant'
    | '/dashboard/units/$id'
    | '/dashboard/units/new-unit'
    | '/dashboard/accounting'
    | '/dashboard/appointments'
    | '/dashboard/buildings'
    | '/dashboard/communications'
    | '/dashboard/contracts'
    | '/dashboard/invoices'
    | '/dashboard/owners'
    | '/dashboard/property-management'
    | '/dashboard/rentals'
    | '/dashboard/reports'
    | '/dashboard/reservations'
    | '/dashboard/service-providers'
    | '/dashboard/settings'
    | '/dashboard/tenants'
    | '/dashboard/units'
    | '/dashboard/accounting/edit-accounting/$id'
    | '/dashboard/appointments/edit-appointment/$id'
    | '/dashboard/buildings/edit-building/$id'
    | '/dashboard/communications/edit-communication/$id'
    | '/dashboard/contracts/edit-contract/$id'
    | '/dashboard/invoices/edit-invoice/$id'
    | '/dashboard/owners/edit-owner/$id'
    | '/dashboard/property-management/edit-property/$id'
    | '/dashboard/rentals/edit-rental/$id'
    | '/dashboard/reports/edit-report/$id'
    | '/dashboard/reservations/edit-reservation/$id'
    | '/dashboard/service-providers/edit-service/$id'
    | '/dashboard/tenants/edit-tenant/$id'
    | '/dashboard/units/edit-unit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/accounting/$id'
    | '/dashboard/accounting/new-accounting'
    | '/dashboard/appointments/$id'
    | '/dashboard/appointments/new-appointment'
    | '/dashboard/buildings/$id'
    | '/dashboard/buildings/new-building'
    | '/dashboard/communications/$id'
    | '/dashboard/communications/new-communication'
    | '/dashboard/contracts/$id'
    | '/dashboard/contracts/new-contract'
    | '/dashboard/invoices/$id'
    | '/dashboard/invoices/new-invoice'
    | '/dashboard/owners/$id'
    | '/dashboard/owners/new-owner'
    | '/dashboard/property-management/$id'
    | '/dashboard/property-management/new-property'
    | '/dashboard/rentals/$id'
    | '/dashboard/rentals/new-rental'
    | '/dashboard/reports/$id'
    | '/dashboard/reports/new-report'
    | '/dashboard/reservations/$id'
    | '/dashboard/reservations/new-reservation'
    | '/dashboard/service-providers/$id'
    | '/dashboard/service-providers/new-service'
    | '/dashboard/tenants/$id'
    | '/dashboard/tenants/new-tenant'
    | '/dashboard/units/$id'
    | '/dashboard/units/new-unit'
    | '/dashboard/accounting'
    | '/dashboard/appointments'
    | '/dashboard/buildings'
    | '/dashboard/communications'
    | '/dashboard/contracts'
    | '/dashboard/invoices'
    | '/dashboard/owners'
    | '/dashboard/property-management'
    | '/dashboard/rentals'
    | '/dashboard/reports'
    | '/dashboard/reservations'
    | '/dashboard/service-providers'
    | '/dashboard/settings'
    | '/dashboard/tenants'
    | '/dashboard/units'
    | '/dashboard/accounting/edit-accounting/$id'
    | '/dashboard/appointments/edit-appointment/$id'
    | '/dashboard/buildings/edit-building/$id'
    | '/dashboard/communications/edit-communication/$id'
    | '/dashboard/contracts/edit-contract/$id'
    | '/dashboard/invoices/edit-invoice/$id'
    | '/dashboard/owners/edit-owner/$id'
    | '/dashboard/property-management/edit-property/$id'
    | '/dashboard/rentals/edit-rental/$id'
    | '/dashboard/reports/edit-report/$id'
    | '/dashboard/reservations/edit-reservation/$id'
    | '/dashboard/service-providers/edit-service/$id'
    | '/dashboard/tenants/edit-tenant/$id'
    | '/dashboard/units/edit-unit/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/accounting/$id'
    | '/dashboard/accounting/new-accounting'
    | '/dashboard/appointments/$id'
    | '/dashboard/appointments/new-appointment'
    | '/dashboard/buildings/$id'
    | '/dashboard/buildings/new-building'
    | '/dashboard/communications/$id'
    | '/dashboard/communications/new-communication'
    | '/dashboard/contracts/$id'
    | '/dashboard/contracts/new-contract'
    | '/dashboard/invoices/$id'
    | '/dashboard/invoices/new-invoice'
    | '/dashboard/owners/$id'
    | '/dashboard/owners/new-owner'
    | '/dashboard/property-management/$id'
    | '/dashboard/property-management/new-property'
    | '/dashboard/rentals/$id'
    | '/dashboard/rentals/new-rental'
    | '/dashboard/reports/$id'
    | '/dashboard/reports/new-report'
    | '/dashboard/reservations/$id'
    | '/dashboard/reservations/new-reservation'
    | '/dashboard/service-providers/$id'
    | '/dashboard/service-providers/new-service'
    | '/dashboard/tenants/$id'
    | '/dashboard/tenants/new-tenant'
    | '/dashboard/units/$id'
    | '/dashboard/units/new-unit'
    | '/dashboard/accounting/'
    | '/dashboard/appointments/'
    | '/dashboard/buildings/'
    | '/dashboard/communications/'
    | '/dashboard/contracts/'
    | '/dashboard/invoices/'
    | '/dashboard/owners/'
    | '/dashboard/property-management/'
    | '/dashboard/rentals/'
    | '/dashboard/reports/'
    | '/dashboard/reservations/'
    | '/dashboard/service-providers/'
    | '/dashboard/settings/'
    | '/dashboard/tenants/'
    | '/dashboard/units/'
    | '/dashboard/accounting/edit-accounting/$id'
    | '/dashboard/appointments/edit-appointment/$id'
    | '/dashboard/buildings/edit-building/$id'
    | '/dashboard/communications/edit-communication/$id'
    | '/dashboard/contracts/edit-contract/$id'
    | '/dashboard/invoices/edit-invoice/$id'
    | '/dashboard/owners/edit-owner/$id'
    | '/dashboard/property-management/edit-property/$id'
    | '/dashboard/rentals/edit-rental/$id'
    | '/dashboard/reports/edit-report/$id'
    | '/dashboard/reservations/edit-reservation/$id'
    | '/dashboard/service-providers/edit-service/$id'
    | '/dashboard/tenants/edit-tenant/$id'
    | '/dashboard/units/edit-unit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/units/': {
      id: '/dashboard/units/'
      path: '/units'
      fullPath: '/dashboard/units'
      preLoaderRoute: typeof DashboardUnitsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tenants/': {
      id: '/dashboard/tenants/'
      path: '/tenants'
      fullPath: '/dashboard/tenants'
      preLoaderRoute: typeof DashboardTenantsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/service-providers/': {
      id: '/dashboard/service-providers/'
      path: '/service-providers'
      fullPath: '/dashboard/service-providers'
      preLoaderRoute: typeof DashboardServiceProvidersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reservations/': {
      id: '/dashboard/reservations/'
      path: '/reservations'
      fullPath: '/dashboard/reservations'
      preLoaderRoute: typeof DashboardReservationsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reports/': {
      id: '/dashboard/reports/'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/rentals/': {
      id: '/dashboard/rentals/'
      path: '/rentals'
      fullPath: '/dashboard/rentals'
      preLoaderRoute: typeof DashboardRentalsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/property-management/': {
      id: '/dashboard/property-management/'
      path: '/property-management'
      fullPath: '/dashboard/property-management'
      preLoaderRoute: typeof DashboardPropertyManagementIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/owners/': {
      id: '/dashboard/owners/'
      path: '/owners'
      fullPath: '/dashboard/owners'
      preLoaderRoute: typeof DashboardOwnersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/invoices/': {
      id: '/dashboard/invoices/'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/contracts/': {
      id: '/dashboard/contracts/'
      path: '/contracts'
      fullPath: '/dashboard/contracts'
      preLoaderRoute: typeof DashboardContractsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/communications/': {
      id: '/dashboard/communications/'
      path: '/communications'
      fullPath: '/dashboard/communications'
      preLoaderRoute: typeof DashboardCommunicationsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/buildings/': {
      id: '/dashboard/buildings/'
      path: '/buildings'
      fullPath: '/dashboard/buildings'
      preLoaderRoute: typeof DashboardBuildingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/appointments/': {
      id: '/dashboard/appointments/'
      path: '/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof DashboardAppointmentsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accounting/': {
      id: '/dashboard/accounting/'
      path: '/accounting'
      fullPath: '/dashboard/accounting'
      preLoaderRoute: typeof DashboardAccountingIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/units/new-unit': {
      id: '/dashboard/units/new-unit'
      path: '/units/new-unit'
      fullPath: '/dashboard/units/new-unit'
      preLoaderRoute: typeof DashboardUnitsNewUnitRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/units/$id': {
      id: '/dashboard/units/$id'
      path: '/units/$id'
      fullPath: '/dashboard/units/$id'
      preLoaderRoute: typeof DashboardUnitsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tenants/new-tenant': {
      id: '/dashboard/tenants/new-tenant'
      path: '/tenants/new-tenant'
      fullPath: '/dashboard/tenants/new-tenant'
      preLoaderRoute: typeof DashboardTenantsNewTenantRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tenants/$id': {
      id: '/dashboard/tenants/$id'
      path: '/tenants/$id'
      fullPath: '/dashboard/tenants/$id'
      preLoaderRoute: typeof DashboardTenantsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/service-providers/new-service': {
      id: '/dashboard/service-providers/new-service'
      path: '/service-providers/new-service'
      fullPath: '/dashboard/service-providers/new-service'
      preLoaderRoute: typeof DashboardServiceProvidersNewServiceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/service-providers/$id': {
      id: '/dashboard/service-providers/$id'
      path: '/service-providers/$id'
      fullPath: '/dashboard/service-providers/$id'
      preLoaderRoute: typeof DashboardServiceProvidersIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reservations/new-reservation': {
      id: '/dashboard/reservations/new-reservation'
      path: '/reservations/new-reservation'
      fullPath: '/dashboard/reservations/new-reservation'
      preLoaderRoute: typeof DashboardReservationsNewReservationRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reservations/$id': {
      id: '/dashboard/reservations/$id'
      path: '/reservations/$id'
      fullPath: '/dashboard/reservations/$id'
      preLoaderRoute: typeof DashboardReservationsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reports/new-report': {
      id: '/dashboard/reports/new-report'
      path: '/reports/new-report'
      fullPath: '/dashboard/reports/new-report'
      preLoaderRoute: typeof DashboardReportsNewReportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reports/$id': {
      id: '/dashboard/reports/$id'
      path: '/reports/$id'
      fullPath: '/dashboard/reports/$id'
      preLoaderRoute: typeof DashboardReportsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/rentals/new-rental': {
      id: '/dashboard/rentals/new-rental'
      path: '/rentals/new-rental'
      fullPath: '/dashboard/rentals/new-rental'
      preLoaderRoute: typeof DashboardRentalsNewRentalRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/rentals/$id': {
      id: '/dashboard/rentals/$id'
      path: '/rentals/$id'
      fullPath: '/dashboard/rentals/$id'
      preLoaderRoute: typeof DashboardRentalsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/property-management/new-property': {
      id: '/dashboard/property-management/new-property'
      path: '/property-management/new-property'
      fullPath: '/dashboard/property-management/new-property'
      preLoaderRoute: typeof DashboardPropertyManagementNewPropertyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/property-management/$id': {
      id: '/dashboard/property-management/$id'
      path: '/property-management/$id'
      fullPath: '/dashboard/property-management/$id'
      preLoaderRoute: typeof DashboardPropertyManagementIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/owners/new-owner': {
      id: '/dashboard/owners/new-owner'
      path: '/owners/new-owner'
      fullPath: '/dashboard/owners/new-owner'
      preLoaderRoute: typeof DashboardOwnersNewOwnerRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/owners/$id': {
      id: '/dashboard/owners/$id'
      path: '/owners/$id'
      fullPath: '/dashboard/owners/$id'
      preLoaderRoute: typeof DashboardOwnersIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/invoices/new-invoice': {
      id: '/dashboard/invoices/new-invoice'
      path: '/invoices/new-invoice'
      fullPath: '/dashboard/invoices/new-invoice'
      preLoaderRoute: typeof DashboardInvoicesNewInvoiceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/invoices/$id': {
      id: '/dashboard/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/dashboard/invoices/$id'
      preLoaderRoute: typeof DashboardInvoicesIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/contracts/new-contract': {
      id: '/dashboard/contracts/new-contract'
      path: '/contracts/new-contract'
      fullPath: '/dashboard/contracts/new-contract'
      preLoaderRoute: typeof DashboardContractsNewContractRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/contracts/$id': {
      id: '/dashboard/contracts/$id'
      path: '/contracts/$id'
      fullPath: '/dashboard/contracts/$id'
      preLoaderRoute: typeof DashboardContractsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/communications/new-communication': {
      id: '/dashboard/communications/new-communication'
      path: '/communications/new-communication'
      fullPath: '/dashboard/communications/new-communication'
      preLoaderRoute: typeof DashboardCommunicationsNewCommunicationRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/communications/$id': {
      id: '/dashboard/communications/$id'
      path: '/communications/$id'
      fullPath: '/dashboard/communications/$id'
      preLoaderRoute: typeof DashboardCommunicationsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/buildings/new-building': {
      id: '/dashboard/buildings/new-building'
      path: '/buildings/new-building'
      fullPath: '/dashboard/buildings/new-building'
      preLoaderRoute: typeof DashboardBuildingsNewBuildingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/buildings/$id': {
      id: '/dashboard/buildings/$id'
      path: '/buildings/$id'
      fullPath: '/dashboard/buildings/$id'
      preLoaderRoute: typeof DashboardBuildingsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/appointments/new-appointment': {
      id: '/dashboard/appointments/new-appointment'
      path: '/appointments/new-appointment'
      fullPath: '/dashboard/appointments/new-appointment'
      preLoaderRoute: typeof DashboardAppointmentsNewAppointmentRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/appointments/$id': {
      id: '/dashboard/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/dashboard/appointments/$id'
      preLoaderRoute: typeof DashboardAppointmentsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accounting/new-accounting': {
      id: '/dashboard/accounting/new-accounting'
      path: '/accounting/new-accounting'
      fullPath: '/dashboard/accounting/new-accounting'
      preLoaderRoute: typeof DashboardAccountingNewAccountingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accounting/$id': {
      id: '/dashboard/accounting/$id'
      path: '/accounting/$id'
      fullPath: '/dashboard/accounting/$id'
      preLoaderRoute: typeof DashboardAccountingIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/units/edit-unit/$id': {
      id: '/dashboard/units/edit-unit/$id'
      path: '/units/edit-unit/$id'
      fullPath: '/dashboard/units/edit-unit/$id'
      preLoaderRoute: typeof DashboardUnitsEditUnitIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tenants/edit-tenant/$id': {
      id: '/dashboard/tenants/edit-tenant/$id'
      path: '/tenants/edit-tenant/$id'
      fullPath: '/dashboard/tenants/edit-tenant/$id'
      preLoaderRoute: typeof DashboardTenantsEditTenantIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/service-providers/edit-service/$id': {
      id: '/dashboard/service-providers/edit-service/$id'
      path: '/service-providers/edit-service/$id'
      fullPath: '/dashboard/service-providers/edit-service/$id'
      preLoaderRoute: typeof DashboardServiceProvidersEditServiceIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reservations/edit-reservation/$id': {
      id: '/dashboard/reservations/edit-reservation/$id'
      path: '/reservations/edit-reservation/$id'
      fullPath: '/dashboard/reservations/edit-reservation/$id'
      preLoaderRoute: typeof DashboardReservationsEditReservationIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reports/edit-report/$id': {
      id: '/dashboard/reports/edit-report/$id'
      path: '/reports/edit-report/$id'
      fullPath: '/dashboard/reports/edit-report/$id'
      preLoaderRoute: typeof DashboardReportsEditReportIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/rentals/edit-rental/$id': {
      id: '/dashboard/rentals/edit-rental/$id'
      path: '/rentals/edit-rental/$id'
      fullPath: '/dashboard/rentals/edit-rental/$id'
      preLoaderRoute: typeof DashboardRentalsEditRentalIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/property-management/edit-property/$id': {
      id: '/dashboard/property-management/edit-property/$id'
      path: '/property-management/edit-property/$id'
      fullPath: '/dashboard/property-management/edit-property/$id'
      preLoaderRoute: typeof DashboardPropertyManagementEditPropertyIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/owners/edit-owner/$id': {
      id: '/dashboard/owners/edit-owner/$id'
      path: '/owners/edit-owner/$id'
      fullPath: '/dashboard/owners/edit-owner/$id'
      preLoaderRoute: typeof DashboardOwnersEditOwnerIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/invoices/edit-invoice/$id': {
      id: '/dashboard/invoices/edit-invoice/$id'
      path: '/invoices/edit-invoice/$id'
      fullPath: '/dashboard/invoices/edit-invoice/$id'
      preLoaderRoute: typeof DashboardInvoicesEditInvoiceIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/contracts/edit-contract/$id': {
      id: '/dashboard/contracts/edit-contract/$id'
      path: '/contracts/edit-contract/$id'
      fullPath: '/dashboard/contracts/edit-contract/$id'
      preLoaderRoute: typeof DashboardContractsEditContractIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/communications/edit-communication/$id': {
      id: '/dashboard/communications/edit-communication/$id'
      path: '/communications/edit-communication/$id'
      fullPath: '/dashboard/communications/edit-communication/$id'
      preLoaderRoute: typeof DashboardCommunicationsEditCommunicationIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/buildings/edit-building/$id': {
      id: '/dashboard/buildings/edit-building/$id'
      path: '/buildings/edit-building/$id'
      fullPath: '/dashboard/buildings/edit-building/$id'
      preLoaderRoute: typeof DashboardBuildingsEditBuildingIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/appointments/edit-appointment/$id': {
      id: '/dashboard/appointments/edit-appointment/$id'
      path: '/appointments/edit-appointment/$id'
      fullPath: '/dashboard/appointments/edit-appointment/$id'
      preLoaderRoute: typeof DashboardAppointmentsEditAppointmentIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accounting/edit-accounting/$id': {
      id: '/dashboard/accounting/edit-accounting/$id'
      path: '/accounting/edit-accounting/$id'
      fullPath: '/dashboard/accounting/edit-accounting/$id'
      preLoaderRoute: typeof DashboardAccountingEditAccountingIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountingIdRoute: typeof DashboardAccountingIdRoute
  DashboardAccountingNewAccountingRoute: typeof DashboardAccountingNewAccountingRoute
  DashboardAppointmentsIdRoute: typeof DashboardAppointmentsIdRoute
  DashboardAppointmentsNewAppointmentRoute: typeof DashboardAppointmentsNewAppointmentRoute
  DashboardBuildingsIdRoute: typeof DashboardBuildingsIdRoute
  DashboardBuildingsNewBuildingRoute: typeof DashboardBuildingsNewBuildingRoute
  DashboardCommunicationsIdRoute: typeof DashboardCommunicationsIdRoute
  DashboardCommunicationsNewCommunicationRoute: typeof DashboardCommunicationsNewCommunicationRoute
  DashboardContractsIdRoute: typeof DashboardContractsIdRoute
  DashboardContractsNewContractRoute: typeof DashboardContractsNewContractRoute
  DashboardInvoicesIdRoute: typeof DashboardInvoicesIdRoute
  DashboardInvoicesNewInvoiceRoute: typeof DashboardInvoicesNewInvoiceRoute
  DashboardOwnersIdRoute: typeof DashboardOwnersIdRoute
  DashboardOwnersNewOwnerRoute: typeof DashboardOwnersNewOwnerRoute
  DashboardPropertyManagementIdRoute: typeof DashboardPropertyManagementIdRoute
  DashboardPropertyManagementNewPropertyRoute: typeof DashboardPropertyManagementNewPropertyRoute
  DashboardRentalsIdRoute: typeof DashboardRentalsIdRoute
  DashboardRentalsNewRentalRoute: typeof DashboardRentalsNewRentalRoute
  DashboardReportsIdRoute: typeof DashboardReportsIdRoute
  DashboardReportsNewReportRoute: typeof DashboardReportsNewReportRoute
  DashboardReservationsIdRoute: typeof DashboardReservationsIdRoute
  DashboardReservationsNewReservationRoute: typeof DashboardReservationsNewReservationRoute
  DashboardServiceProvidersIdRoute: typeof DashboardServiceProvidersIdRoute
  DashboardServiceProvidersNewServiceRoute: typeof DashboardServiceProvidersNewServiceRoute
  DashboardTenantsIdRoute: typeof DashboardTenantsIdRoute
  DashboardTenantsNewTenantRoute: typeof DashboardTenantsNewTenantRoute
  DashboardUnitsIdRoute: typeof DashboardUnitsIdRoute
  DashboardUnitsNewUnitRoute: typeof DashboardUnitsNewUnitRoute
  DashboardAccountingIndexRoute: typeof DashboardAccountingIndexRoute
  DashboardAppointmentsIndexRoute: typeof DashboardAppointmentsIndexRoute
  DashboardBuildingsIndexRoute: typeof DashboardBuildingsIndexRoute
  DashboardCommunicationsIndexRoute: typeof DashboardCommunicationsIndexRoute
  DashboardContractsIndexRoute: typeof DashboardContractsIndexRoute
  DashboardInvoicesIndexRoute: typeof DashboardInvoicesIndexRoute
  DashboardOwnersIndexRoute: typeof DashboardOwnersIndexRoute
  DashboardPropertyManagementIndexRoute: typeof DashboardPropertyManagementIndexRoute
  DashboardRentalsIndexRoute: typeof DashboardRentalsIndexRoute
  DashboardReportsIndexRoute: typeof DashboardReportsIndexRoute
  DashboardReservationsIndexRoute: typeof DashboardReservationsIndexRoute
  DashboardServiceProvidersIndexRoute: typeof DashboardServiceProvidersIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardTenantsIndexRoute: typeof DashboardTenantsIndexRoute
  DashboardUnitsIndexRoute: typeof DashboardUnitsIndexRoute
  DashboardAccountingEditAccountingIdRoute: typeof DashboardAccountingEditAccountingIdRoute
  DashboardAppointmentsEditAppointmentIdRoute: typeof DashboardAppointmentsEditAppointmentIdRoute
  DashboardBuildingsEditBuildingIdRoute: typeof DashboardBuildingsEditBuildingIdRoute
  DashboardCommunicationsEditCommunicationIdRoute: typeof DashboardCommunicationsEditCommunicationIdRoute
  DashboardContractsEditContractIdRoute: typeof DashboardContractsEditContractIdRoute
  DashboardInvoicesEditInvoiceIdRoute: typeof DashboardInvoicesEditInvoiceIdRoute
  DashboardOwnersEditOwnerIdRoute: typeof DashboardOwnersEditOwnerIdRoute
  DashboardPropertyManagementEditPropertyIdRoute: typeof DashboardPropertyManagementEditPropertyIdRoute
  DashboardRentalsEditRentalIdRoute: typeof DashboardRentalsEditRentalIdRoute
  DashboardReportsEditReportIdRoute: typeof DashboardReportsEditReportIdRoute
  DashboardReservationsEditReservationIdRoute: typeof DashboardReservationsEditReservationIdRoute
  DashboardServiceProvidersEditServiceIdRoute: typeof DashboardServiceProvidersEditServiceIdRoute
  DashboardTenantsEditTenantIdRoute: typeof DashboardTenantsEditTenantIdRoute
  DashboardUnitsEditUnitIdRoute: typeof DashboardUnitsEditUnitIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountingIdRoute: DashboardAccountingIdRoute,
  DashboardAccountingNewAccountingRoute: DashboardAccountingNewAccountingRoute,
  DashboardAppointmentsIdRoute: DashboardAppointmentsIdRoute,
  DashboardAppointmentsNewAppointmentRoute:
    DashboardAppointmentsNewAppointmentRoute,
  DashboardBuildingsIdRoute: DashboardBuildingsIdRoute,
  DashboardBuildingsNewBuildingRoute: DashboardBuildingsNewBuildingRoute,
  DashboardCommunicationsIdRoute: DashboardCommunicationsIdRoute,
  DashboardCommunicationsNewCommunicationRoute:
    DashboardCommunicationsNewCommunicationRoute,
  DashboardContractsIdRoute: DashboardContractsIdRoute,
  DashboardContractsNewContractRoute: DashboardContractsNewContractRoute,
  DashboardInvoicesIdRoute: DashboardInvoicesIdRoute,
  DashboardInvoicesNewInvoiceRoute: DashboardInvoicesNewInvoiceRoute,
  DashboardOwnersIdRoute: DashboardOwnersIdRoute,
  DashboardOwnersNewOwnerRoute: DashboardOwnersNewOwnerRoute,
  DashboardPropertyManagementIdRoute: DashboardPropertyManagementIdRoute,
  DashboardPropertyManagementNewPropertyRoute:
    DashboardPropertyManagementNewPropertyRoute,
  DashboardRentalsIdRoute: DashboardRentalsIdRoute,
  DashboardRentalsNewRentalRoute: DashboardRentalsNewRentalRoute,
  DashboardReportsIdRoute: DashboardReportsIdRoute,
  DashboardReportsNewReportRoute: DashboardReportsNewReportRoute,
  DashboardReservationsIdRoute: DashboardReservationsIdRoute,
  DashboardReservationsNewReservationRoute:
    DashboardReservationsNewReservationRoute,
  DashboardServiceProvidersIdRoute: DashboardServiceProvidersIdRoute,
  DashboardServiceProvidersNewServiceRoute:
    DashboardServiceProvidersNewServiceRoute,
  DashboardTenantsIdRoute: DashboardTenantsIdRoute,
  DashboardTenantsNewTenantRoute: DashboardTenantsNewTenantRoute,
  DashboardUnitsIdRoute: DashboardUnitsIdRoute,
  DashboardUnitsNewUnitRoute: DashboardUnitsNewUnitRoute,
  DashboardAccountingIndexRoute: DashboardAccountingIndexRoute,
  DashboardAppointmentsIndexRoute: DashboardAppointmentsIndexRoute,
  DashboardBuildingsIndexRoute: DashboardBuildingsIndexRoute,
  DashboardCommunicationsIndexRoute: DashboardCommunicationsIndexRoute,
  DashboardContractsIndexRoute: DashboardContractsIndexRoute,
  DashboardInvoicesIndexRoute: DashboardInvoicesIndexRoute,
  DashboardOwnersIndexRoute: DashboardOwnersIndexRoute,
  DashboardPropertyManagementIndexRoute: DashboardPropertyManagementIndexRoute,
  DashboardRentalsIndexRoute: DashboardRentalsIndexRoute,
  DashboardReportsIndexRoute: DashboardReportsIndexRoute,
  DashboardReservationsIndexRoute: DashboardReservationsIndexRoute,
  DashboardServiceProvidersIndexRoute: DashboardServiceProvidersIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardTenantsIndexRoute: DashboardTenantsIndexRoute,
  DashboardUnitsIndexRoute: DashboardUnitsIndexRoute,
  DashboardAccountingEditAccountingIdRoute:
    DashboardAccountingEditAccountingIdRoute,
  DashboardAppointmentsEditAppointmentIdRoute:
    DashboardAppointmentsEditAppointmentIdRoute,
  DashboardBuildingsEditBuildingIdRoute: DashboardBuildingsEditBuildingIdRoute,
  DashboardCommunicationsEditCommunicationIdRoute:
    DashboardCommunicationsEditCommunicationIdRoute,
  DashboardContractsEditContractIdRoute: DashboardContractsEditContractIdRoute,
  DashboardInvoicesEditInvoiceIdRoute: DashboardInvoicesEditInvoiceIdRoute,
  DashboardOwnersEditOwnerIdRoute: DashboardOwnersEditOwnerIdRoute,
  DashboardPropertyManagementEditPropertyIdRoute:
    DashboardPropertyManagementEditPropertyIdRoute,
  DashboardRentalsEditRentalIdRoute: DashboardRentalsEditRentalIdRoute,
  DashboardReportsEditReportIdRoute: DashboardReportsEditReportIdRoute,
  DashboardReservationsEditReservationIdRoute:
    DashboardReservationsEditReservationIdRoute,
  DashboardServiceProvidersEditServiceIdRoute:
    DashboardServiceProvidersEditServiceIdRoute,
  DashboardTenantsEditTenantIdRoute: DashboardTenantsEditTenantIdRoute,
  DashboardUnitsEditUnitIdRoute: DashboardUnitsEditUnitIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
